// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Alignment alignment2;
    
    private Gtk.VBox vbox4;
    
    private Gtk.ScrolledWindow scrolledwindow1;
    
    private Gtk.TextView TTV_first;
    
    private Gtk.HBox hbox1;
    
    private Gtk.ComboBox CB_first;
    
    private Gtk.Button B_change;
    
    private Gtk.HBox hbox2;
    
    private Gtk.ComboBox CB_second;
    
    private Gtk.Button B_translate;
    
    private Gtk.ScrolledWindow scrolledwindow3;
    
    private Gtk.TextView TTV_second;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("GoogleTranslate");
        this.Icon = new Gdk.Pixbuf(System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "./res/icon.png"));
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.alignment2 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
        this.alignment2.Name = "alignment2";
        this.alignment2.LeftPadding = ((uint)(6));
        this.alignment2.TopPadding = ((uint)(6));
        this.alignment2.RightPadding = ((uint)(6));
        this.alignment2.BottomPadding = ((uint)(6));
        // Container child alignment2.Gtk.Container+ContainerChild
        this.vbox4 = new Gtk.VBox();
        this.vbox4.CanDefault = true;
        this.vbox4.Name = "vbox4";
        this.vbox4.Spacing = 6;
        // Container child vbox4.Gtk.Box+BoxChild
        this.scrolledwindow1 = new Gtk.ScrolledWindow();
        this.scrolledwindow1.CanFocus = true;
        this.scrolledwindow1.Name = "scrolledwindow1";
        this.scrolledwindow1.HscrollbarPolicy = ((Gtk.PolicyType)(2));
        this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child scrolledwindow1.Gtk.Container+ContainerChild
        Gtk.Viewport w1 = new Gtk.Viewport();
        w1.ShadowType = ((Gtk.ShadowType)(0));
        // Container child GtkViewport.Gtk.Container+ContainerChild
        this.TTV_first = new Gtk.TextView();
        this.TTV_first.CanFocus = true;
        this.TTV_first.Name = "TTV_first";
        this.TTV_first.WrapMode = ((Gtk.WrapMode)(2));
        w1.Add(this.TTV_first);
        this.scrolledwindow1.Add(w1);
        this.vbox4.Add(this.scrolledwindow1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox4[this.scrolledwindow1]));
        w4.Position = 0;
        // Container child vbox4.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.CB_first = Gtk.ComboBox.NewText();
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Albanian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Arabic"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Bulgarian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Catalan"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Chinese (Simplified)"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Chinese (Traditional)"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Croatian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Czech"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Danish"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Dutch"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("English"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Estonian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Filipino"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Finnish"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("French"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Galician"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("German"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Greek"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Hebrew"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Hindi"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Hungarian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Indonesian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Italian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Japanese"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Korean"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Latvian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Lithuanian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Maltese"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Norwegian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Polish"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Portuguese"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Romanian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Russian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Serbian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Slovak"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Slovenian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Spanish"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Swedish"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Thai"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Turkish"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Ukrainian"));
        this.CB_first.AppendText(Mono.Unix.Catalog.GetString("Vietnamese"));
        this.CB_first.Name = "CB_first";
        this.CB_first.Active = 32;
        this.hbox1.Add(this.CB_first);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.CB_first]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.B_change = new Gtk.Button();
        this.B_change.CanFocus = true;
        this.B_change.Name = "B_change";
        this.B_change.UseUnderline = true;
        // Container child B_change.Gtk.Container+ContainerChild
        Gtk.Alignment w6 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w7 = new Gtk.HBox();
        w7.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w8 = new Gtk.Image();
        w8.Pixbuf = new Gdk.Pixbuf(System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "./res/swap.png"));
        w7.Add(w8);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w10 = new Gtk.Label();
        w7.Add(w10);
        w6.Add(w7);
        this.B_change.Add(w6);
        this.hbox1.Add(this.B_change);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox1[this.B_change]));
        w14.Position = 1;
        w14.Expand = false;
        w14.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.CB_second = Gtk.ComboBox.NewText();
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Albanian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Arabic"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Bulgarian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Catalan"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Chinese (Simplified)"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Chinese (Traditional)"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Croatian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Czech"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Danish"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Dutch"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("English"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Estonian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Filipino"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Finnish"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("French"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Galician"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("German"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Greek"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Hebrew"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Hindi"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Hungarian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Indonesian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Italian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Japanese"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Korean"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Latvian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Lithuanian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Maltese"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Norwegian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Polish"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Portuguese"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Romanian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Russian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Serbian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Slovak"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Slovenian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Spanish"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Swedish"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Thai"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Turkish"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Ukrainian"));
        this.CB_second.AppendText(Mono.Unix.Catalog.GetString("Vietnamese"));
        this.CB_second.Name = "CB_second";
        this.CB_second.Active = 10;
        this.hbox2.Add(this.CB_second);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox2[this.CB_second]));
        w15.Position = 0;
        w15.Expand = false;
        w15.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.B_translate = new Gtk.Button();
        this.B_translate.CanFocus = true;
        this.B_translate.Name = "B_translate";
        this.B_translate.UseUnderline = true;
        this.B_translate.Label = Mono.Unix.Catalog.GetString("Translate");
        this.hbox2.Add(this.B_translate);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox2[this.B_translate]));
        w16.Position = 1;
        w16.Expand = false;
        w16.Fill = false;
        this.hbox1.Add(this.hbox2);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
        w17.Position = 2;
        w17.Expand = false;
        w17.Fill = false;
        this.vbox4.Add(this.hbox1);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
        w18.Position = 1;
        w18.Expand = false;
        w18.Fill = false;
        // Container child vbox4.Gtk.Box+BoxChild
        this.scrolledwindow3 = new Gtk.ScrolledWindow();
        this.scrolledwindow3.CanFocus = true;
        this.scrolledwindow3.Name = "scrolledwindow3";
        this.scrolledwindow3.HscrollbarPolicy = ((Gtk.PolicyType)(2));
        this.scrolledwindow3.ShadowType = ((Gtk.ShadowType)(1));
        // Container child scrolledwindow3.Gtk.Container+ContainerChild
        Gtk.Viewport w19 = new Gtk.Viewport();
        w19.ShadowType = ((Gtk.ShadowType)(0));
        // Container child GtkViewport2.Gtk.Container+ContainerChild
        this.TTV_second = new Gtk.TextView();
        this.TTV_second.CanFocus = true;
        this.TTV_second.Name = "TTV_second";
        this.TTV_second.AcceptsTab = false;
        w19.Add(this.TTV_second);
        this.scrolledwindow3.Add(w19);
        this.vbox4.Add(this.scrolledwindow3);
        Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox4[this.scrolledwindow3]));
        w22.Position = 2;
        this.alignment2.Add(this.vbox4);
        this.Add(this.alignment2);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 443;
        this.DefaultHeight = 302;
        this.vbox4.HasDefault = true;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.Mapped += new System.EventHandler(this.OnMapped);
        this.B_change.Clicked += new System.EventHandler(this.OnBChangeClicked);
        this.B_translate.Clicked += new System.EventHandler(this.OnBTranslateClicked);
    }
}
